
name: Update Version

concurrency: ci-version

on: 
  push:
  schedule:
    - cron:  '00 * * * *'
  workflow_dispatch:
    
jobs:
  
  update_latest:
    name: Update version
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    timeout-minutes: 10
    
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Install CLI
      run: |
        curl --silent --location https://vault.bitwarden.com/download/?app=cli&platform=linux | unzip

    - name: Get latest version
      id: version
      run: |
        VER=$(bw --version)
        echo "version=$VER" >> $GITHUB_ENV

    - name: Write latest version to file
      run: echo -n ${{ env.version }} > VERSION

    - name: Commit and push changes
      id: push
      uses: devops-infra/action-commit-push@v0.9.2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        commit_message: Updated to version ${{ env.version }}

  #build:
  #  
  #  name: Chocolatey Build
  #  runs-on: windows-latest
  #  timeout-minutes: 15
  #  steps:
  #  - uses: actions/checkout@v3
#